name: build the jdk yes very cool

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: refresh apt lists
      run: sudo apt update -y
    - name: install build-deps
      run: sudo apt install libfontconfig-dev libcups2-dev libx11-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev libxt-dev libasound2-dev build-essential openjdk-17-jdk -y
    - uses: actions/checkout@v3
    - name: chmod it
      run: chmod +x ./configure
    - name: configure
      run: ./configure
    - name: make images
      run: make images
    - name: zip it
      run: zip -q -r jdk17u-nosleeps.zip *
    - name: store jdk
      uses: actions/upload-artifact@v4.1.0
      with:
        name: jdk17u-nosleeps
        path: jdk17u-nosleeps.zip
            
